
DROP TABLE IF EXISTS T_BANK_ACCOUNT;
DROP TABLE IF EXISTS T_BANK_RECORD;

CREATE TABLE T_BANK_ACCOUNT
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT '主键',
    account    VARCHAR(256) NOT NULL COMMENT '账号',
    company    VARCHAR(256) NOT NULL COMMENT '公司名称',
    legal      VARCHAR(256) NOT NULL COMMENT '法人',
    balance    DOUBLE COMMENT '余额',
    createTime DATETIME NOT NULL COMMENT '开户时间'
);
CREATE UNIQUE INDEX T_BANK_ACCOUNT_IDX1 ON T_BANK_ACCOUNT_IDX1 (account);

CREATE TABLE T_BANK_RECORD
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT '主键',
    account    VARCHAR(256) NOT NULL COMMENT '账号',
    op_type    VARCHAR(256) NOT NULL COMMENT '操作',
    op_time    VARCHAR(256) NOT NULL COMMENT '操作时间',
    amount     DOUBLE COMMENT '发生金额',
    balance    DOUBLE COMMENT '余额'
);
CREATE UNIQUE INDEX T_BANK_RECORD_IDX1 ON T_BANK_RECORD (account, op_time);